import type { Metadata } from "next";
import { Header, Footer, GoogleAnalytics } from "@/app/_components";
import { footerData, headerData } from "./_lib/data";
import "@/app/_styles/globals.scss";

export const metadata: Metadata = {
  title: {
    default: "Supreme BARF Canine | Alimento superior para perro",
    template: "%s - Supreme BARF Canine",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleAnalytics />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/vvp5ave.css"
        ></link>
      </head>

      <body>
        <Header
          data={headerData.data}
          frontPageID={headerData.frontPageID}
          elevation={2}
        />
        {children}
        <Footer
          footerMenuDataPrimary={footerData.footerMenuDataPrimary}
          footerMenuDataSecondary={footerData.footerMenuDataSecondary}
          footerPoliticsData={footerData.footerPoliticsData}
          frontPageID={footerData.frontPageID}
          options={footerData.options}
        />
      </body>
    </html>
  );
}
