import type { Metadata } from "next";
import Image from "next/image";
import { raleway } from "@/app/_fonts";
import { Header, Footer, GoogleAnalytics } from "@/app/_components"; // Asegúrate de importar GoogleAnalytics
import { footerPayload, payloadPrimary } from "./_lib/data";
import whatsappImage from "@/public/whatsapp.png";
import "@/app/_styles/globals.scss";

export const metadata: Metadata = {
  title: {
    default: "Supreme BARF Canine | Alimento superior para perro",
    template: "%s - Supreme BARF Canine",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleAnalytics />
      </head>
      <body className={`${raleway.className}`}>
        <Header
          data={payloadPrimary.data}
          frontPageID={payloadPrimary.frontPageID}
          elevation={2}
        />
        {children}

        <Footer
          footerMenuDataPrimary={footerPayload.footerMenuDataPrimary}
          footerMenuDataSecondary={footerPayload.footerMenuDataSecondary}
          footerPoliticsData={footerPayload.footerPoliticsData}
          frontPageID={footerPayload.frontPageID}
          options={footerPayload.options}
        />

        <a
          href="https://wa.me/+5215649395148"
          className="whatsapp-float"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image src={whatsappImage} alt="WhatsApp" width="50" height="50" />
        </a>
      </body>
    </html>
  );
}
